### ISSUE TITLE
doesn't work on handhend machines

### ISSUE THREAD

**Issue by bakeiro** [Woflox/intoruins#1]
Hi!

I tried this game online and works flawlessly, the thing is, when I try it in a handhend device it doesn't work, I'm using [R36S](https://thegamepadgamer.com/2023/11/i-cant-believe-this-is-only-40-r36s-review/) and it loads the first screen, but when the caracter should fall down to the cave never happens, I guess some kind of code exception happens there, any change that this could be solved?

thanks in advance!

**Comment by Woflox** [comment]
Hi, is your device connected to wifi? If not it's probably trying to load the 2nd cart from the BBS and failing.

Alternatively, you can try the offline carts found here: [https://github.com/Woflox/intoruins/tree/master/carts/offline](https://github.com/Woflox/intoruins/tree/master/carts/offline)

Those shouldn't require an internet connection. Just put them somewhere your device can find them and make sure they're in the same folder, launch intoruins.p8.png, and it should work. They're also available as a zipped download [on itch](https://sparsegamedev.itch.io/into-ruins)

**Comment by bakeiro** [comment]
oh, thanks for the quick reply, I'm gonna try it today and will tell U if works!

**Comment by bakeiro** [comment]
ok, it works!
