### ISSUE TITLE
2 offline carts?

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [Woflox/intoruins#2]
Just wondering why there are 2 carts in the offline carts zip. Do I need them in the same folder, or are they separate halves of the game?

**Comment by Vortigern-The-Grey** [comment]
nvm, read forum post. My bad

**Comment by Vortigern-The-Grey** [comment]
Actually, how do I play? is the first cart meant to trigger the second?

**Comment by Vortigern-The-Grey** [comment]
here is the error
![image](https://github.com/Woflox/intoruins/assets/152357748/1fbca402-cdb2-4d98-8ee0-232bbd95da05)

**Comment by Woflox** [comment]
Yes, the game needs both carts to run and they should be in the same folder. Apologies for not providing the information on github -- maybe in the release section? Or I could just add a readme text with the carts.

You might be loading the wrong one -- if you load intoruins.p8.png it should work. This cart contains the title screen and also puts some data in memory that the intoruins_main cart needs.

Let me know if you still get an error.

**Comment by Vortigern-The-Grey** [comment]
Yeah, just found out they need to be in the carts folder. I was dragging them onto the shortcut on the desktop, so even though they were in the same folder, that folder wasn't the carts folder. Great game tho!

**Comment by clort81** [comment]
I wish i had the time to study your work.  But thanks on behalf of the future conscious entities who will have time to study it.
